var PRISSS_SHOWS = [  { title: "Regenr8 @ The Richmond 23 Nov 2019", url: "https://www.mixcloud.com/Prisss/regenr8-the-richmond-23-nov-2019/" },
  { title: "PsychoTronic Hypno-Twist : Modify the Inside Without Electrodes", url: "https://www.mixcloud.com/Prisss/psychotronic-hypno-twist/" },
  { title: "Robot Disco - Bee's Mouth 15 June 2019", url: "https://www.mixcloud.com/Prisss/robot-disco-bees-mouth-15-june-2019/" },
  { title: "Factory at TrickStar Radio 2 February 2019 pt2", url: "https://www.mixcloud.com/Prisss/factory-at-trickstar-radio-2-february-2019-pt2/" },
  { title: "Factory at TrickStar Radio 2 February 2019 pt1", url: "https://www.mixcloud.com/Prisss/factory-at-trickstar-radio-2-february-2019-pt1/" },
  { title: "Spookie at Beep's Mouth 2018", url: "https://www.mixcloud.com/Prisss/spookie-at-beeps-mouth-2018/" },
  { title: "Slammin' Techno at [beep]'s Mouth 21 July 2018", url: "https://www.mixcloud.com/Prisss/slammin-techno-at-beeps-mouth-21-july-2018/" },
  { title: "NYE  2017 [beep] Full On Flat White Techno Prisss", url: "https://www.mixcloud.com/Prisss/nye-2017-beep-full-on-flat-white-techno-prisss/" },
  { title: "Post-Cryptobi­­osis [beep] Speakers Corner Pride 5 August 2017", url: "https://www.mixcloud.com/Prisss/post-cryptobiosis-beep-speakers-corner-pride-5-august-2017/" },
  { title: "Summer Trip for HMDS on Code South 31 May 2017", url: "https://www.mixcloud.com/Prisss/summer-trip-for-hmds-on-code-south-31-may-2017/" },
  { title: "The Pied Piper of my Heart  - The Verdict 6th May 2017", url: "https://www.mixcloud.com/Prisss/the-pied-piper-of-my-heart/" },
  { title: "[beep]#4 PRISSS - Their Game Is UP ! Lawyers File For Obama's Arrest !", url: "https://www.mixcloud.com/Prisss/beep4-prisss-their-game-is-up-lawyers-file-for-obamas-arrest/" },
  { title: "Music is Essentially Playfull", url: "https://www.mixcloud.com/Prisss/music-is-essentially-playfull/" },
  { title: "Berlin Mixtape 009 - Beyond Imagination", url: "https://www.mixcloud.com/Prisss/berlin-mixtape-009-beyond-imagination/" },
  { title: "The Robots are Here & You Should be Worried", url: "https://www.mixcloud.com/Prisss/the-robots-are-here-you-should-be-worried/" },
  { title: "Open Sound Collective 24 November 2016", url: "https://www.mixcloud.com/Prisss/open-sound-collective-24-november-2016/" },
  { title: "[beep] Coloured Memories - 1 October 2016", url: "https://www.mixcloud.com/Prisss/beep-coloured-memories-1-october-2016/" },
  { title: "Code South - Lunar Transmission - 27 August 2016", url: "https://www.mixcloud.com/Prisss/code-south-lunar-transmission-27-august-2016/" },
  { title: "[beep] 5 December 2015", url: "https://www.mixcloud.com/Prisss/beep-5-december-2015/" },
  { title: "The Ship is Ready : Arbiters of Sanity", url: "https://www.mixcloud.com/Prisss/the-ship-is-ready-arbiters-of-sanity/" },
  { title: "Angels are Real", url: "https://www.mixcloud.com/Prisss/angels-are-real/" },
  { title: "Splitting The Atom 2 August 2015", url: "https://www.mixcloud.com/Prisss/splitting-the-atom-2-august-2015/" },
  { title: "Prisss vs Arboria Auralist @ The Living Room 10 May 2015", url: "https://www.mixcloud.com/Prisss/prisss-vs-arboria-auralist-the-living-room-10-may-2015/" },
  { title: "Ocean Rock Thailand pt2 Spring 2015", url: "https://www.mixcloud.com/Prisss/ocean-rock-thailand-pt2-spring-2015/" },
  { title: "Ocean Rock Thailand pt1 Spring 2015", url: "https://www.mixcloud.com/Prisss/ocean-rock-thailand-pt1-spring-2015/" },
  { title: "New Year's Eve Warehouse Party @ Brighton Arts Club 2014 / 15", url: "https://www.mixcloud.com/Prisss/new-years-eve-warehouse-party-brighton-arts-club-2014/" },
  { title: "Breaking Robots at Spirit of Gravity 27 November 2014", url: "https://www.mixcloud.com/Prisss/breaking-robots-at-spirit-of-gravity-27-november-2014/" },
  { title: "Instances of bull shit are on the increase...", url: "https://www.mixcloud.com/Prisss/instances-of-bull-shit-are-on-the-increase/" },
  { title: "Most indigenous populations say \"Fuck Patience\"", url: "https://www.mixcloud.com/Prisss/most-indigenous-populations-say-fuck-patience/" },
  { title: "Follow The Instructions Breaking Robots 6/9/14", url: "https://www.mixcloud.com/Prisss/follow-the-instructions/" },
  { title: "Lakeside View - Breaking Robots [2/3]  - August 2014", url: "https://www.mixcloud.com/Prisss/lakeside-view/" },
  { title: "BREAKING ROBOTS live set for [beep]stock Festival - Brighton - 19 July 2014", url: "https://www.mixcloud.com/Prisss/beepstock-festiveal-brighton-19-july-2014/" },
  { title: "Brighton Arts Club 23 May 2014", url: "https://www.mixcloud.com/Prisss/brighton-arts-club-23-may-2014/" },
  { title: "Music got that groove: pumping, pumping, pumping...", url: "https://www.mixcloud.com/Prisss/music-got-that-groove-pumping-pumping-pumping/" },
  { title: "Big-ass pumping funk", url: "https://www.mixcloud.com/Prisss/big-ass-pumping-funk/" },
  { title: "Explosions will continually shake the Earth !", url: "https://www.mixcloud.com/Prisss/explosions-will-continually-shake-the-earth/" },
  { title: "Ms Moneypenny's beach bake", url: "https://www.mixcloud.com/Prisss/ms-moneypennys-beach-bake/" },
  { title: "Funk the Funk", url: "https://www.mixcloud.com/Prisss/fatbeaches2nov13/" },
  { title: "[beep]#3 The Specimen inside the cylindrical chamber has been compromised", url: "https://www.mixcloud.com/Prisss/the-specimen-inside-the-cylindrical-chamber-has-been-compromised/" },
  { title: "Minimize session 23 October 2013", url: "https://www.mixcloud.com/Prisss/minimize-session-23-october-2013/" },
  { title: "FatBeaches Pretox Session", url: "https://www.mixcloud.com/Prisss/fatbeaches-pretox-session/" },
  { title: "Minimize session 24 July 2013", url: "https://www.mixcloud.com/Prisss/minimize-session-24-july-2013/" },
  { title: "Garden of Uneartly Delights pt2", url: "https://www.mixcloud.com/Prisss/garden-of-uneartly-delights-pt2/" },
  { title: "Garden of Uneartly Delights pt1", url: "https://www.mixcloud.com/Prisss/garden-of-uneartly-delights-pt1/" },
  { title: "Finding Diamonds [beep]#2", url: "https://www.mixcloud.com/Prisss/finding-diamonds/" },
  { title: "Miss Money Penny's 'Pillow Biter [stopped by the cops] Sunrise Set' - part 1", url: "https://www.mixcloud.com/Prisss/miss-money-pennys-pillow-biter-stopped-by-the-cops-sunrise-set-part-1/" },
  { title: "Stone Bar 12 April 2013 - Tribal Underground Mix - part 2", url: "https://www.mixcloud.com/Prisss/stone-bar-12-april-2013-tribal-underground-mix-part-2/" },
  { title: "Stone Bar 12 April 2013 - Tribal Underground Mix - part 1", url: "https://www.mixcloud.com/Prisss/stone-bar-12-april-2013-tribal-underground-mix-part-1/" },
  { title: "Stone Bar 28 February 2013", url: "https://www.mixcloud.com/Prisss/stone-bar-28-february-2013/" },
  { title: "Peace & Love 12 February 2013 part 3", url: "https://www.mixcloud.com/Prisss/peace-love-12-february-2013-part-3/" },
];
